// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pharaohsLegacy.Models;

#nullable disable

namespace pharaohsLegacy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728082135_AddItemViewsAndSecretBadges")]
    partial class AddItemViewsAndSecretBadges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pharaohsLegacy.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentLocationAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Museum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuseumAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Visit",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "زار 3 أماكن",
                            DescriptionEn = "Visited 3 places",
                            IconClass = "fa-solid fa-compass",
                            IsHidden = false,
                            Key = "explorer",
                            NameAr = "مستكشف",
                            NameEn = "Explorer",
                            Threshold = 3,
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Visit",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "زار 7 أماكن",
                            DescriptionEn = "Visited 7 places",
                            IconClass = "fa-solid fa-compass",
                            IsHidden = false,
                            Key = "explorer",
                            NameAr = "سيد المعابد",
                            NameEn = "Temple Master",
                            Threshold = 7,
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Visit",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "زار 15 مكان",
                            DescriptionEn = "Visited 15 places",
                            IconClass = "fa-solid fa-compass",
                            IsHidden = false,
                            Key = "explorer",
                            NameAr = "المستكشف الأعظم",
                            NameEn = "Grand Explorer",
                            Threshold = 15,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "أضاف 5 فراعنة للمفضلة",
                            DescriptionEn = "Favorited 5 pharaohs",
                            IconClass = "fa-solid fa-crown",
                            IsHidden = false,
                            Key = "pharaoh_expert",
                            NameAr = "خبير الفراعنة",
                            NameEn = "Pharaoh Expert",
                            Threshold = 5,
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "أضاف 15 فرعون للمفضلة",
                            DescriptionEn = "Favorited 15 pharaohs",
                            IconClass = "fa-solid fa-crown",
                            IsHidden = false,
                            Key = "pharaoh_expert",
                            NameAr = "خبير الفراعنة",
                            NameEn = "Pharaoh Expert",
                            Threshold = 15,
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "أضاف 30 فرعون للمفضلة",
                            DescriptionEn = "Favorited 30 pharaohs",
                            IconClass = "fa-solid fa-crown",
                            IsHidden = false,
                            Key = "pharaoh_expert",
                            NameAr = "خبير الفراعنة",
                            NameEn = "Pharaoh Expert",
                            Threshold = 30,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "استكشف 5 أسرات",
                            DescriptionEn = "Explored 5 dynasties",
                            IconClass = "fa-solid fa-scroll",
                            IsHidden = false,
                            Key = "dynasty_expert",
                            NameAr = "خبير الأسرات",
                            NameEn = "Dynasty Expert",
                            Threshold = 5,
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "استكشف 15 أسرة",
                            DescriptionEn = "Explored 15 dynasties",
                            IconClass = "fa-solid fa-scroll",
                            IsHidden = false,
                            Key = "dynasty_expert",
                            NameAr = "خبير الأسرات",
                            NameEn = "Dynasty Expert",
                            Threshold = 15,
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "استكشف 30 أسرة",
                            DescriptionEn = "Explored 30 dynasties",
                            IconClass = "fa-solid fa-scroll",
                            IsHidden = false,
                            Key = "dynasty_expert",
                            NameAr = "خبير الأسرات",
                            NameEn = "Dynasty Expert",
                            Threshold = 30,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Community",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "كتب 3 مراجعات",
                            DescriptionEn = "Wrote 3 reviews",
                            IconClass = "fa-solid fa-pen",
                            IsHidden = false,
                            Key = "reviewer",
                            NameAr = "كاتب مراجعات",
                            NameEn = "Reviewer",
                            Threshold = 3,
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Community",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "كتب 10 مراجعات",
                            DescriptionEn = "Wrote 10 reviews",
                            IconClass = "fa-solid fa-pen",
                            IsHidden = false,
                            Key = "reviewer",
                            NameAr = "كاتب مراجعات",
                            NameEn = "Reviewer",
                            Threshold = 10,
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Community",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "كتب 25 مراجعة",
                            DescriptionEn = "Wrote 25 reviews",
                            IconClass = "fa-solid fa-pen",
                            IsHidden = false,
                            Key = "reviewer",
                            NameAr = "كاتب مراجعات",
                            NameEn = "Reviewer",
                            Threshold = 25,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Community",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "حصل على 5 أصوات مفيدة",
                            DescriptionEn = "Got 5 helpful votes",
                            IconClass = "fa-solid fa-handshake-angle",
                            IsHidden = false,
                            Key = "community_helper",
                            NameAr = "مساعد المجتمع",
                            NameEn = "Community Helper",
                            Threshold = 5,
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Community",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "حصل على 20 صوت مفيد",
                            DescriptionEn = "Got 20 helpful votes",
                            IconClass = "fa-solid fa-handshake-angle",
                            IsHidden = false,
                            Key = "community_helper",
                            NameAr = "مساعد المجتمع",
                            NameEn = "Community Helper",
                            Threshold = 20,
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Community",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "حصل على 50 صوت مفيد",
                            DescriptionEn = "Got 50 helpful votes",
                            IconClass = "fa-solid fa-handshake-angle",
                            IsHidden = false,
                            Key = "community_helper",
                            NameAr = "مساعد المجتمع",
                            NameEn = "Community Helper",
                            Threshold = 50,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "لعب 5 كويزات أو وصل لاستمرارية 3 أيام",
                            DescriptionEn = "Played 5 quizzes or reached a 3-day streak",
                            IconClass = "fa-solid fa-brain",
                            IsHidden = false,
                            Key = "quiz_master",
                            NameAr = "سيد الأسئلة",
                            NameEn = "Quiz Master",
                            Threshold = 5,
                            Tier = "Bronze"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "لعب 20 كويز أو وصل لاستمرارية 7 أيام",
                            DescriptionEn = "Played 20 quizzes or reached a 7-day streak",
                            IconClass = "fa-solid fa-brain",
                            IsHidden = false,
                            Key = "quiz_master",
                            NameAr = "سيد الأسئلة",
                            NameEn = "Quiz Master",
                            Threshold = 20,
                            Tier = "Silver"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Knowledge",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "لعب 50 كويز أو وصل لاستمرارية 30 يوم",
                            DescriptionEn = "Played 50 quizzes or reached a 30-day streak",
                            IconClass = "fa-solid fa-brain",
                            IsHidden = false,
                            Key = "quiz_master",
                            NameAr = "سيد الأسئلة",
                            NameEn = "Quiz Master",
                            Threshold = 50,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Legendary",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "حصل على الذهبي في كل شارة تانية",
                            DescriptionEn = "Earned Gold in every other badge",
                            IconClass = "fa-solid fa-trophy",
                            IsHidden = false,
                            Key = "legendary_explorer",
                            NameAr = "المستكشف الأسطوري",
                            NameEn = "Legendary Explorer",
                            Threshold = 0,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Hidden",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "حقق 100% في كويز",
                            DescriptionEn = "Scored 100% on a quiz",
                            IconClass = "fa-solid fa-star",
                            IsHidden = true,
                            Key = "perfect_score",
                            NameAr = "الدرجة الكاملة",
                            NameEn = "Perfect Score",
                            Threshold = 1,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Hidden",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "وصل لاستمرارية 30 يوم في الكويز",
                            DescriptionEn = "Reached a 30-day quiz streak",
                            IconClass = "fa-solid fa-fire",
                            IsHidden = true,
                            Key = "streak_legend",
                            NameAr = "أسطورة الاستمرارية",
                            NameEn = "Streak Legend",
                            Threshold = 30,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Hidden",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "زار كل المتاحف",
                            DescriptionEn = "Visited every museum",
                            IconClass = "fa-solid fa-building-columns",
                            IsHidden = true,
                            Key = "museum_completionist",
                            NameAr = "جامع المتاحف",
                            NameEn = "Museum Completionist",
                            Threshold = 42,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Hidden",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "استكشف كل الأسرات",
                            DescriptionEn = "Explored every dynasty",
                            IconClass = "fa-solid fa-landmark-dome",
                            IsHidden = true,
                            Key = "true_historian",
                            NameAr = "المؤرخ الحقيقي",
                            NameEn = "True Historian",
                            Threshold = 35,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Hidden",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "عضو من سنة كاملة",
                            DescriptionEn = "Member for a full year",
                            IconClass = "fa-solid fa-heart",
                            IsHidden = true,
                            Key = "loyal_explorer",
                            NameAr = "المستكشف الوفي",
                            NameEn = "Loyal Explorer",
                            Threshold = 365,
                            Tier = "Gold"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Hidden",
                            CreatedAt = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionAr = "حجز زيارة أو لعب كويز الساعة 3 الفجر",
                            DescriptionEn = "Booked a visit or played a quiz at 3 AM",
                            IconClass = "fa-solid fa-moon",
                            IsHidden = true,
                            Key = "night_owl",
                            NameAr = "بومة الليل",
                            NameEn = "Night Owl",
                            Threshold = 1,
                            Tier = "Gold"
                        });
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.DailyFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactTextAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DailyFacts");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Dynasty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AchievementsAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapitalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapitalCityAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EraAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharaohTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dynasties");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.God", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gods");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.HistoricalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DynastyTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharaohTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricalEvents");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ItemView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail", "Type", "ItemId")
                        .IsUnique();

                    b.ToTable("ItemViews");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Monument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Monuments");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Museum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Founded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Museums");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Pharaoh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dynasty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DynastyAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pharaohs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Known as Ramesses the Great, he reigned for 66 years and built the temples of Abu Simbel.",
                            Dynasty = "19th Dynasty",
                            ImageUrl = "/images/pharaohs/ramesses2_child2.jpg",
                            Name = "Ramesses II",
                            Period = "1279–1213 BC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The boy pharaoh whose intact tomb, discovered in 1922, revealed the splendors of ancient Egypt.",
                            Dynasty = "18th Dynasty",
                            ImageUrl = "/images/pharaohs/tutankhamun_crop.jpg",
                            Name = "Tutankhamun",
                            Period = "1332–1323 BC"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The last active ruler of the Ptolemaic Kingdom of Egypt, known for her intelligence and alliances with Rome.",
                            Dynasty = "Ptolemaic Dynasty",
                            ImageUrl = "/images/pharaohs/cleopatra.jpg",
                            Name = "Cleopatra VII",
                            Period = "51–30 BC"
                        });
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceType", "PlaceId")
                        .IsUnique();

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimensionsAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginRegionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.QuizHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("ScorePercent")
                        .HasColumnType("int");

                    b.Property<int>("StreakDays")
                        .HasColumnType("int");

                    b.Property<bool>("StreakEligible")
                        .HasColumnType("bit");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuizHistories");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ReviewHelpful", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReviewHelpfuls");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ReviewReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReporterEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReviewReports");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.SearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SearchHistories");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ShopOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShopOrders");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ShopOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShopOrderId");

                    b.ToTable("ShopOrderItems");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ShopPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopOrderId");

                    b.ToTable("ShopPayments");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Temple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Temples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The largest ancient religious site in the world, dedicated to the god Amun.",
                            ImageUrl = "/images/temples/karnak3.jpg",
                            Latitude = 0.0,
                            Location = "Luxor, Egypt",
                            Longitude = 0.0,
                            Name = "Karnak Temple",
                            Period = "2055–100 BC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Two massive rock temples built by Ramesses II, relocated to avoid flooding from the Nile.",
                            ImageUrl = "/images/temples/abusimbel.jpg",
                            Latitude = 0.0,
                            Location = "Aswan, Egypt",
                            Longitude = 0.0,
                            Name = "Abu Simbel",
                            Period = "1264–1244 BC"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A large ancient Egyptian temple complex located on the east bank of the Nile River.",
                            ImageUrl = "/images/temples/luxor2.jpg",
                            Latitude = 0.0,
                            Location = "Luxor, Egypt",
                            Longitude = 0.0,
                            Name = "Luxor Temple",
                            Period = "1400 BC"
                        });
                });

            modelBuilder.Entity("pharaohsLegacy.Models.TripPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TripPlans");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.TripPlanStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripPlanId");

                    b.ToTable("TripPlanStops");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Payment", b =>
                {
                    b.HasOne("pharaohsLegacy.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.Product", b =>
                {
                    b.HasOne("pharaohsLegacy.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ShopOrderItem", b =>
                {
                    b.HasOne("pharaohsLegacy.Models.ShopOrder", "ShopOrder")
                        .WithMany("Items")
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopOrder");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ShopPayment", b =>
                {
                    b.HasOne("pharaohsLegacy.Models.ShopOrder", "ShopOrder")
                        .WithMany()
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopOrder");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.TripPlanStop", b =>
                {
                    b.HasOne("pharaohsLegacy.Models.TripPlan", "TripPlan")
                        .WithMany("Stops")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.ShopOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("pharaohsLegacy.Models.TripPlan", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
